---
- name: Block IP address using UFW
  hosts: localhost
  become: yes
  tasks:
    - name: Check if UFW is installed
      command: ufw --version
      ignore_errors: yes
      register: ufw_installed

    - name: Install UFW if not installed
      apt:
        name: ufw
        state: present
      when: ufw_installed.rc != 0

    - name: Block IP address
      command: ufw deny from 192.168.56.104
